### ISSUE TITLE
npmjs.com publishing

### ISSUE THREAD

**Issue by haoyunfeix** [01org/widl-nan#11]
We need publish widl-nan on https://www.npmjs.com/ so that nodejs users can easily find and use this tool.

**Comment by kenny-y** [comment]
@halton In what npmjs user name we want to publish this repo? I've created a npmjs user with my work email but what's the proper name for it?

**Comment by halton** [comment]
Refer RealSenese windows modules, (search crosswalk-extension on npmjs.com), I do not see big problem if you use your work email.

**Comment by kenny-y** [comment]
I see some had identified themselves as Intel employee using "at intel" suffix, while some hadn't. I'll go ahead with the suffix way.

**Comment by kenny-y** [comment]
It's done now. https://www.npmjs.com/package/widl-nan
