### ISSUE TITLE
static operation support

### ISSUE THREAD

**Issue by haoyunfeix** [01org/widl-nan#6]
https://www.w3.org/TR/WebIDL/#idl-static-operations
`interface Point { /* ... */ };`

```
interface Circle {
  attribute float cx;
  attribute float cy;
  attribute float radius;

  static Point triangulate(Circle c1, Circle c2, Circle c3);
};
```

**Comment by haoyunfeix** [comment]
Halton's commit:
Looking at a dictionary example in Blink, [DOMPoint.idl](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/dom/DOMPointInit.idl?q=DOMPointInit.idl&sq=package:chromium&dr), the generated C++ code is as [DOMPointInit.cpp](https://cs.chromium.org/chromium/src/out/Debug/gen/blink/core/dom/DOMPointInit.h?sq=package:chromium&d) and [DOMPointInit.h](https://cs.chromium.org/chromium/src/out/Debug/gen/blink/core/dom/DOMPointInit.h?sq=package:chromium&dr), we can do same thing in widl-nan.

**Comment by kenny-y** [comment]
The support to static operation is currently present, so close this directly.
