### ISSUE TITLE
ArrayBuffer object freed mutiple times when garbage collected

### ISSUE THREAD

**Issue by tingshao** [01org/widl-nan#72]
Each ArrayBuffer property access will generate a v8 object but with the same internal buffer.
When garbage collection is triggered, the internal buffer will be freeed multiple times
It's better that each access of the ArrayBuffer property doesn't create new objects.

**Comment by halton** [comment]
@tingshao is the PR submitted here?

**Comment by tingshao** [comment]
@halton Yes, this is the issue for the PR. I may close it manually.

**Comment by halton** [comment]
Please use the github PR closing mechanism as much as possible.

**Comment by tingshao** [comment]
OK.

**Comment by kenny-y** [comment]
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by tingshao** [comment]
@kenny-y Thanks a lot for the reference.

**Comment by tingshao** [comment]
@kenny-y Can you help to close this? It seems I have no permission.

**Comment by kenny-y** [comment]
I kinda lost context here... is this an already-fixed issue (with PR merged) but the issue itself is still open? In it's that case, I'll close it directly.

**Comment by tingshao** [comment]
Yes, already fixed.
